// CKD-relevant food database (per serving)
// Values from USDA FoodData Central, rounded for usability.
// Tags: 'low-k' (<200mg K), 'low-p' (<100mg P), 'low-na' (<140mg Na), 'avoid' (high in 2+ restricted nutrients)

window.FOOD_DB = [
  // ───── Fruits ─────
  { cat: 'Fruits', name: 'Apple, medium',          serving: '1 fruit',       sodium: 2,   potassium: 195, phosphorus: 20,  protein: 0.5, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Applesauce',             serving: '1/2 cup',       sodium: 2,   potassium: 91,  phosphorus: 8,   protein: 0.2, fluids: 4, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Banana, medium',         serving: '1 fruit',       sodium: 1,   potassium: 422, phosphorus: 26,  protein: 1.3, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Fruits', name: 'Blueberries',            serving: '1/2 cup',       sodium: 1,   potassium: 57,  phosphorus: 9,   protein: 0.5, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Cantaloupe',             serving: '1 cup cubed',   sodium: 26,  potassium: 427, phosphorus: 27,  protein: 1.3, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Fruits', name: 'Cherries',               serving: '1/2 cup',       sodium: 0,   potassium: 175, phosphorus: 16,  protein: 1,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Cranberries, fresh',     serving: '1/2 cup',       sodium: 1,   potassium: 43,  phosphorus: 6,   protein: 0.2, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Grapes',                 serving: '1/2 cup',       sodium: 1,   potassium: 144, phosphorus: 15,  protein: 0.5, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Orange, medium',         serving: '1 fruit',       sodium: 0,   potassium: 237, phosphorus: 18,  protein: 1.2, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Fruits', name: 'Peach, medium',          serving: '1 fruit',       sodium: 0,   potassium: 285, phosphorus: 30,  protein: 1.4, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Fruits', name: 'Pear, medium',           serving: '1 fruit',       sodium: 2,   potassium: 206, phosphorus: 20,  protein: 0.7, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Fruits', name: 'Pineapple, fresh',       serving: '1/2 cup',       sodium: 1,   potassium: 90,  phosphorus: 6,   protein: 0.5, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Strawberries',           serving: '1/2 cup',       sodium: 1,   potassium: 127, phosphorus: 19,  protein: 0.5, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Watermelon',             serving: '1 cup cubed',   sodium: 2,   potassium: 170, phosphorus: 17,  protein: 0.9, fluids: 5, tags: ['low-k','low-p','low-na'] },
  { cat: 'Fruits', name: 'Avocado',                serving: '1/2 fruit',     sodium: 7,   potassium: 487, phosphorus: 52,  protein: 2,   fluids: 0, tags: [] },
  { cat: 'Fruits', name: 'Raisins',                serving: '1/4 cup',       sodium: 4,   potassium: 270, phosphorus: 36,  protein: 1,   fluids: 0, tags: [] },

  // ───── Vegetables ─────
  { cat: 'Vegetables', name: 'Asparagus, cooked',  serving: '1/2 cup',       sodium: 13,  potassium: 202, phosphorus: 49,  protein: 2.2, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Vegetables', name: 'Bell pepper, raw',   serving: '1/2 cup',       sodium: 2,   potassium: 110, phosphorus: 14,  protein: 0.5, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Broccoli, cooked',   serving: '1/2 cup',       sodium: 32,  potassium: 229, phosphorus: 52,  protein: 1.9, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Vegetables', name: 'Cabbage, raw',       serving: '1 cup',         sodium: 16,  potassium: 151, phosphorus: 23,  protein: 1.1, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Carrots, raw',       serving: '1 medium',      sodium: 42,  potassium: 195, phosphorus: 21,  protein: 0.6, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Cauliflower, cooked',serving: '1/2 cup',       sodium: 9,   potassium: 88,  phosphorus: 20,  protein: 1,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Celery, raw',        serving: '1 stalk',       sodium: 32,  potassium: 104, phosphorus: 9,   protein: 0.3, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Corn, cooked',       serving: '1/2 cup',       sodium: 14,  potassium: 196, phosphorus: 84,  protein: 2.6, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Cucumber, raw',      serving: '1/2 cup',       sodium: 1,   potassium: 76,  phosphorus: 12,  protein: 0.3, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Green beans, cooked',serving: '1/2 cup',       sodium: 1,   potassium: 91,  phosphorus: 18,  protein: 1.2, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Lettuce, romaine',   serving: '1 cup',         sodium: 4,   potassium: 116, phosphorus: 17,  protein: 0.6, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Onion, raw',         serving: '1/4 cup',       sodium: 1,   potassium: 58,  phosphorus: 11,  protein: 0.3, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Spinach, cooked',    serving: '1/2 cup',       sodium: 63,  potassium: 419, phosphorus: 50,  protein: 2.7, fluids: 0, tags: [] },
  { cat: 'Vegetables', name: 'Squash, summer',     serving: '1/2 cup',       sodium: 1,   potassium: 173, phosphorus: 35,  protein: 0.8, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Vegetables', name: 'Tomato, raw',        serving: '1 medium',      sodium: 6,   potassium: 292, phosphorus: 30,  protein: 1.1, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Vegetables', name: 'Zucchini, cooked',   serving: '1/2 cup',       sodium: 3,   potassium: 238, phosphorus: 39,  protein: 0.7, fluids: 0, tags: ['low-p','low-na'] },
  { cat: 'Vegetables', name: 'Potato, baked',      serving: '1 medium',      sodium: 17,  potassium: 926, phosphorus: 121, protein: 4.3, fluids: 0, tags: [] },
  { cat: 'Vegetables', name: 'Sweet potato, baked',serving: '1 medium',      sodium: 71,  potassium: 542, phosphorus: 61,  protein: 2.3, fluids: 0, tags: ['low-p'] },
  { cat: 'Vegetables', name: 'Mushrooms, cooked',  serving: '1/2 cup',       sodium: 2,   potassium: 277, phosphorus: 43,  protein: 1.7, fluids: 0, tags: ['low-p','low-na'] },

  // ───── Grains ─────
  { cat: 'Grains', name: 'White rice, cooked',     serving: '1 cup',         sodium: 1,   potassium: 55,  phosphorus: 68,  protein: 4.3, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Grains', name: 'Brown rice, cooked',     serving: '1 cup',         sodium: 8,   potassium: 174, phosphorus: 162, protein: 5,   fluids: 0, tags: ['low-k','low-na'] },
  { cat: 'Grains', name: 'Pasta, cooked',          serving: '1 cup',         sodium: 6,   potassium: 62,  phosphorus: 58,  protein: 8,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Grains', name: 'White bread',            serving: '1 slice',       sodium: 150, potassium: 35,  phosphorus: 25,  protein: 2.5, fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Grains', name: 'Whole wheat bread',      serving: '1 slice',       sodium: 144, potassium: 81,  phosphorus: 57,  protein: 3.6, fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Grains', name: 'Oatmeal, cooked',        serving: '1 cup',         sodium: 9,   potassium: 164, phosphorus: 180, protein: 5.9, fluids: 4, tags: ['low-k','low-na'] },
  { cat: 'Grains', name: 'Cereal, corn flakes',    serving: '1 cup',         sodium: 200, potassium: 30,  phosphorus: 8,   protein: 1.9, fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Grains', name: 'Bagel, plain',           serving: '1 medium',      sodium: 451, potassium: 81,  phosphorus: 79,  protein: 9,   fluids: 0, tags: [] },
  { cat: 'Grains', name: 'Tortilla, flour',        serving: '1 medium',      sodium: 304, potassium: 50,  phosphorus: 60,  protein: 4,   fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Grains', name: 'Crackers, saltines',     serving: '5 crackers',    sodium: 156, potassium: 17,  phosphorus: 11,  protein: 1,   fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Grains', name: 'Quinoa, cooked',         serving: '1 cup',         sodium: 13,  potassium: 318, phosphorus: 281, protein: 8,   fluids: 0, tags: ['low-na'] },

  // ───── Proteins ─────
  { cat: 'Proteins', name: 'Chicken breast',       serving: '3 oz cooked',   sodium: 75,  potassium: 220, phosphorus: 196, protein: 27,  fluids: 0, tags: ['low-na'] },
  { cat: 'Proteins', name: 'Chicken thigh',        serving: '3 oz cooked',   sodium: 78,  potassium: 196, phosphorus: 162, protein: 21,  fluids: 0, tags: ['low-k','low-na'] },
  { cat: 'Proteins', name: 'Turkey breast',        serving: '3 oz cooked',   sodium: 54,  potassium: 251, phosphorus: 196, protein: 26,  fluids: 0, tags: ['low-na'] },
  { cat: 'Proteins', name: 'Beef, lean ground',    serving: '3 oz cooked',   sodium: 66,  potassium: 270, phosphorus: 155, protein: 22,  fluids: 0, tags: ['low-na'] },
  { cat: 'Proteins', name: 'Pork loin',            serving: '3 oz cooked',   sodium: 48,  potassium: 380, phosphorus: 188, protein: 22,  fluids: 0, tags: ['low-na'] },
  { cat: 'Proteins', name: 'Salmon, cooked',       serving: '3 oz cooked',   sodium: 50,  potassium: 326, phosphorus: 218, protein: 22,  fluids: 0, tags: ['low-na'] },
  { cat: 'Proteins', name: 'Tuna, canned in water',serving: '3 oz drained',  sodium: 247, potassium: 201, phosphorus: 139, protein: 22,  fluids: 0, tags: [] },
  { cat: 'Proteins', name: 'Cod, cooked',          serving: '3 oz cooked',   sodium: 66,  potassium: 207, phosphorus: 117, protein: 19,  fluids: 0, tags: ['low-na'] },
  { cat: 'Proteins', name: 'Shrimp',               serving: '3 oz cooked',   sodium: 161, potassium: 220, phosphorus: 137, protein: 20,  fluids: 0, tags: [] },
  { cat: 'Proteins', name: 'Egg, whole',           serving: '1 large',       sodium: 70,  potassium: 63,  phosphorus: 86,  protein: 6,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Proteins', name: 'Egg white',            serving: '1 large',       sodium: 55,  potassium: 54,  phosphorus: 5,   protein: 3.6, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Proteins', name: 'Tofu, firm',           serving: '3 oz',          sodium: 6,   potassium: 154, phosphorus: 161, protein: 9,   fluids: 0, tags: ['low-k','low-na'] },
  { cat: 'Proteins', name: 'Hot dog',              serving: '1 link',        sodium: 510, potassium: 76,  phosphorus: 51,  protein: 5,   fluids: 0, tags: [] },
  { cat: 'Proteins', name: 'Bacon',                serving: '2 slices',      sodium: 360, potassium: 102, phosphorus: 80,  protein: 6,   fluids: 0, tags: [] },
  { cat: 'Proteins', name: 'Ham, deli',            serving: '2 oz',          sodium: 730, potassium: 200, phosphorus: 130, protein: 10,  fluids: 0, tags: [] },
  { cat: 'Proteins', name: 'Peanut butter',        serving: '2 tbsp',        sodium: 152, potassium: 208, phosphorus: 107, protein: 7,   fluids: 0, tags: [] },

  // ───── Dairy & Alternatives ─────
  { cat: 'Dairy', name: 'Milk, 2%',                serving: '8 oz',          sodium: 115, potassium: 366, phosphorus: 251, protein: 8,   fluids: 8, tags: [] },
  { cat: 'Dairy', name: 'Milk, skim',              serving: '8 oz',          sodium: 103, potassium: 382, phosphorus: 247, protein: 8,   fluids: 8, tags: [] },
  { cat: 'Dairy', name: 'Almond milk, unsweet.',   serving: '8 oz',          sodium: 150, potassium: 160, phosphorus: 20,  protein: 1,   fluids: 8, tags: ['low-k','low-p'] },
  { cat: 'Dairy', name: 'Rice milk',               serving: '8 oz',          sodium: 86,  potassium: 65,  phosphorus: 56,  protein: 0.7, fluids: 8, tags: ['low-k','low-p','low-na'] },
  { cat: 'Dairy', name: 'Soy milk',                serving: '8 oz',          sodium: 90,  potassium: 287, phosphorus: 119, protein: 7,   fluids: 8, tags: ['low-na'] },
  { cat: 'Dairy', name: 'Yogurt, plain low-fat',   serving: '6 oz',          sodium: 117, potassium: 440, phosphorus: 247, protein: 9,   fluids: 4, tags: [] },
  { cat: 'Dairy', name: 'Greek yogurt, plain',     serving: '6 oz',          sodium: 65,  potassium: 240, phosphorus: 168, protein: 17,  fluids: 4, tags: ['low-na'] },
  { cat: 'Dairy', name: 'Cheese, cheddar',         serving: '1 oz',          sodium: 180, potassium: 28,  phosphorus: 145, protein: 7,   fluids: 0, tags: ['low-k'] },
  { cat: 'Dairy', name: 'Cheese, mozzarella',      serving: '1 oz',          sodium: 175, potassium: 21,  phosphorus: 105, protein: 7,   fluids: 0, tags: ['low-k'] },
  { cat: 'Dairy', name: 'Cottage cheese, low-fat', serving: '1/2 cup',       sodium: 459, potassium: 105, phosphorus: 169, protein: 14,  fluids: 0, tags: ['low-k'] },
  { cat: 'Dairy', name: 'Cream cheese',            serving: '2 tbsp',        sodium: 90,  potassium: 38,  phosphorus: 30,  protein: 2,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Dairy', name: 'Butter',                  serving: '1 tbsp',        sodium: 90,  potassium: 3,   phosphorus: 3,   protein: 0.1, fluids: 0, tags: ['low-k','low-p','low-na'] },

  // ───── Beverages ─────
  { cat: 'Beverages', name: 'Water',               serving: '8 oz',          sodium: 0,   potassium: 0,   phosphorus: 0,   protein: 0,   fluids: 8, tags: ['low-k','low-p','low-na'] },
  { cat: 'Beverages', name: 'Coffee, black',       serving: '8 oz',          sodium: 5,   potassium: 116, phosphorus: 7,   protein: 0.3, fluids: 8, tags: ['low-k','low-p','low-na'] },
  { cat: 'Beverages', name: 'Tea, brewed',         serving: '8 oz',          sodium: 7,   potassium: 88,  phosphorus: 3,   protein: 0,   fluids: 8, tags: ['low-k','low-p','low-na'] },
  { cat: 'Beverages', name: 'Lemonade',            serving: '8 oz',          sodium: 7,   potassium: 37,  phosphorus: 4,   protein: 0.2, fluids: 8, tags: ['low-k','low-p','low-na'] },
  { cat: 'Beverages', name: 'Cola',                serving: '12 oz',         sodium: 15,  potassium: 4,   phosphorus: 41,  protein: 0,   fluids: 12, tags: ['low-k','low-na'] },
  { cat: 'Beverages', name: 'Apple juice',         serving: '8 oz',          sodium: 10,  potassium: 250, phosphorus: 18,  protein: 0.5, fluids: 8, tags: ['low-p'] },
  { cat: 'Beverages', name: 'Orange juice',        serving: '8 oz',          sodium: 2,   potassium: 496, phosphorus: 42,  protein: 1.7, fluids: 8, tags: ['low-na'] },
  { cat: 'Beverages', name: 'Cranberry juice',     serving: '8 oz',          sodium: 5,   potassium: 195, phosphorus: 32,  protein: 0,   fluids: 8, tags: ['low-k','low-p','low-na'] },
  { cat: 'Beverages', name: 'Beer, regular',       serving: '12 oz',         sodium: 14,  potassium: 96,  phosphorus: 50,  protein: 1.6, fluids: 12, tags: ['low-k','low-p','low-na'] },
  { cat: 'Beverages', name: 'Wine, red',           serving: '5 oz',          sodium: 6,   potassium: 187, phosphorus: 34,  protein: 0.1, fluids: 5, tags: ['low-p','low-na'] },
  { cat: 'Beverages', name: 'Sports drink',        serving: '8 oz',          sodium: 110, potassium: 30,  phosphorus: 0,   protein: 0,   fluids: 8, tags: ['low-k','low-p'] },

  // ───── Snacks ─────
  { cat: 'Snacks', name: 'Pretzels',               serving: '1 oz',          sodium: 359, potassium: 41,  phosphorus: 33,  protein: 2.6, fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Snacks', name: 'Popcorn, air-popped',    serving: '3 cups',        sodium: 1,   potassium: 80,  phosphorus: 84,  protein: 3,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Snacks', name: 'Potato chips',           serving: '1 oz',          sodium: 149, potassium: 361, phosphorus: 47,  protein: 1.8, fluids: 0, tags: [] },
  { cat: 'Snacks', name: 'Tortilla chips',         serving: '1 oz',          sodium: 119, potassium: 56,  phosphorus: 65,  protein: 2,   fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Snacks', name: 'Animal crackers',        serving: '8 cookies',     sodium: 130, potassium: 23,  phosphorus: 18,  protein: 1.6, fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Snacks', name: 'Graham crackers',        serving: '2 squares',     sodium: 90,  potassium: 28,  phosphorus: 16,  protein: 1,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Snacks', name: 'Vanilla wafers',         serving: '4 cookies',     sodium: 65,  potassium: 13,  phosphorus: 13,  protein: 1,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Snacks', name: 'Almonds',                serving: '1 oz (~23)',    sodium: 0,   potassium: 208, phosphorus: 137, protein: 6,   fluids: 0, tags: ['low-na'] },
  { cat: 'Snacks', name: 'Walnuts',                serving: '1 oz (~14)',    sodium: 1,   potassium: 125, phosphorus: 98,  protein: 4.3, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Snacks', name: 'Pumpkin seeds',          serving: '1 oz',          sodium: 5,   potassium: 226, phosphorus: 333, protein: 9,   fluids: 0, tags: [] },

  // ───── Other / Condiments ─────
  { cat: 'Other', name: 'Olive oil',               serving: '1 tbsp',        sodium: 0,   potassium: 0,   phosphorus: 0,   protein: 0,   fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Other', name: 'Mayonnaise',              serving: '1 tbsp',        sodium: 88,  potassium: 5,   phosphorus: 4,   protein: 0.1, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Other', name: 'Mustard',                 serving: '1 tsp',         sodium: 57,  potassium: 7,   phosphorus: 4,   protein: 0.2, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Other', name: 'Ketchup',                 serving: '1 tbsp',        sodium: 167, potassium: 60,  phosphorus: 4,   protein: 0.2, fluids: 0, tags: ['low-k','low-p'] },
  { cat: 'Other', name: 'Soy sauce',               serving: '1 tbsp',        sodium: 879, potassium: 32,  phosphorus: 19,  protein: 1.3, fluids: 0, tags: [] },
  { cat: 'Other', name: 'Honey',                   serving: '1 tbsp',        sodium: 1,   potassium: 11,  phosphorus: 1,   protein: 0.1, fluids: 0, tags: ['low-k','low-p','low-na'] },
  { cat: 'Other', name: 'Sugar',                   serving: '1 tsp',         sodium: 0,   potassium: 0,   phosphorus: 0,   protein: 0,   fluids: 0, tags: ['low-k','low-p','low-na'] },
];

window.QUESTION_TEMPLATES = [
  { cat: 'Labs',     text: 'What does my latest eGFR trend tell us?' },
  { cat: 'Labs',     text: 'Are any of my numbers outside target ranges?' },
  { cat: 'Labs',     text: 'When should we recheck labs?' },
  { cat: 'Labs',     text: 'Should we test for proteinuria (UACR)?' },
  { cat: 'Meds',     text: 'Should any of my current medications be adjusted?' },
  { cat: 'Meds',     text: 'Are there over-the-counter medications I should avoid?' },
  { cat: 'Meds',     text: 'Should I be on an SGLT2 inhibitor or finerenone?' },
  { cat: 'Meds',     text: 'Is my current ACE inhibitor / ARB dose correct?' },
  { cat: 'Diet',     text: 'Do I need to restrict potassium more strictly?' },
  { cat: 'Diet',     text: 'How much protein per day is right for my stage?' },
  { cat: 'Diet',     text: 'Should I see a renal dietitian?' },
  { cat: 'Diet',     text: 'How much fluid should I drink daily?' },
  { cat: 'BP',       text: 'Is my blood pressure home-monitoring data adequate?' },
  { cat: 'BP',       text: 'Should I adjust my BP target?' },
  { cat: 'Symptoms', text: 'Is my fatigue level concerning?' },
  { cat: 'Symptoms', text: 'Should swelling at this level prompt action?' },
  { cat: 'Symptoms', text: 'What symptoms warrant calling the office vs ER?' },
  { cat: 'Lifestyle',text: 'What level of exercise is safe and helpful?' },
  { cat: 'Lifestyle',text: 'Any vaccines I should be up to date on?' },
  { cat: 'Planning', text: 'When should we discuss dialysis or transplant prep?' },
  { cat: 'Planning', text: 'Should I see a nephrologist subspecialist?' },
];
